url: http://lafrikitiva.com
permalink: /:year/:i_month/:i_day/:title.html
exclude: [Rakefile, Gemfile, Gemfile.lock, README.markdown, Capfile, bin, s3_website.yml, tmp]
paginate: 3
name: La Frikitiva
description: Diario de un filólogo en Dinamarca.
